jewelry/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^', include('shop.urls')),
    re_path(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import include
from django.urls import re_path
from . import views

app_name = 'shop'

urlpatterns = [
    re_path(r'^login/$', views.login_user, name='login'),
    re_path(r'^logout/$', views.logout_user, name='logout'),
    re_path(r'$', views.index, name='home'),
    re_path(r'^jewellery/$', views.index),
    # re_path(r'^/rings/$', views.showRings, name='rings'),
    # re_path(r'^/neckless/$', views.showNeckless, name = 'neckless'),
    re_path(r'^about/$', views.about, name='about'),
    re_path(r'^thank/$', views.thankYouPage , name='thank'),
    re_path(r'^register/$', views.register, name='register'),
    re_path(r'^cart/$', views.cart, name='cart'),
    re_path(r'^addToCart/(?P<qty>([^/]+))/(?P<buy_id>[0-9]+)/$', views.setQty, name = 'qty'),
    re_path(r'^detail/(?P<product_id>[0-9]+)/$', views.detailproduct, name='detail'),
    re_path(r'^detail/(?P<product_id>[0-9]+)/saved$', views.saveReview, name='saveReview'),
    re_path(r'^addToCart/(?P<product_id>[0-9]+)/$',views.addToCart, name = 'addToCart'),
    re_path(r'^addToCart/(?P<buy_id>[0-9]+)/unbuy$', views.removeFromCart, name = 'remove'),
    re_path(r'^checkout/$', views.checkout, name='checkout'),
]

shop/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class MetalType(models.Model):
    metal_type = models.CharField(max_length = 30)

    def __unicode__(self):
        return self.metal_type

class Category(models.Model):
    metal_type = models.ForeignKey(MetalType,on_delete=models.CASCADE)
    c_name = models.CharField(max_length = 50)

    def __unicode__(self):
        return self.c_name

class Product(models.Model):
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    p_name = models.CharField(max_length = 100)
    p_detail = models.TextField()
    p_cost = models.DecimalField(max_digits = 10, decimal_places = 2)
    p_photo = models.ImageField(blank=True, upload_to='product_photo')

    def __unicode__(self):
        return u'%s - %s: %f ' % (self.p_name, self.category.c_name ,self.p_cost)

class ReviewProduct(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    review = models.TextField()
    rating = models.IntegerField(default = 1)

    def __unicode__(self):
        return u'%s : %s : %s' % (self.user.username, self.product.p_name, self.review)

class ItemPurchase(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    is_purchased = models.BooleanField(default=False)
    quantity = models.IntegerField(default=0)

    def __unicode__(self):
        return u'%s : %s ' % (self.user.username, self.product.p_name)

class ShoppingDetail(models.Model):
    full_name = models.CharField(max_length = 100)
    street = models.CharField(max_length = 100)
    town = models.CharField(max_length = 100)
    district = models.CharField(max_length = 100)
    state = models.CharField(max_length = 100)
    country = models.CharField(max_length = 100)
    pin = models.IntegerField()

    def __unicode__(self):
        return u'%s : %s %d' %(self.full_name, self.country, self.pin)

shop/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import ReviewProduct, ShoppingDetail

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username','email','password']

class ReviewForm(forms.ModelForm):
	class Meta:
		model = ReviewProduct
		fields = ['review', 'rating']

class ShoppingDetailForm(forms.ModelForm):
    class Meta:
        model = ShoppingDetail
        fields = ['full_name', 'street', 'town', 'district', 'state', 'country', 'pin']

shop/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from .models import *
from .forms import *
from django.http import HttpResponseRedirect, HttpResponse
# Create your views here.

def cart(request):
    buyList = ItemPurchase.objects.all()
    length = len(buyList)
    return render(request, 'shop/cart.html', {'buyList':buyList, 'length':length, 'user':request.user})

def addToCart(request, product_id):
    buyPr = ItemPurchase()
    buyPr.user = request.user
    buyPr.product = Product.objects.get(pk = product_id)
    if buyPr.is_purchased:
        buyPr.is_purchased = False
    else:
        buyPr.is_purchased = True
    buyPr.quantity = 1
    buyPr.save()
    return HttpResponseRedirect('/jewellery')

def setQty(request, qty, buy_id):
    buyPr = ItemPurchase.objects.get(pk = buy_id)
    buyPr.quantity = int(qty)
    buyPr.save()
    return HttpResponseRedirect('/cart')

def index(request):
    if not request.user.is_authenticated:
        return render(request, 'shop/login.html')
    else:
        products = Product.objects.all()
        corproducts = products[:4]
        context = {'products':products, 'user':request.user, 'corproducts':corproducts}
        return render(request, 'shop/index.html', context)

def register(request):
    form = UserForm(request.POST)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect('/jewellery')
            else:
                return HttpResponseRedirect('/register')
        else:
            return render(request, 'shop/register.html', {'form':form})
    return render(request, 'shop/register.html',{'form':form})

def login_user(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect('/jewellery')
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        print(user)
        if user is not None:
            if user.is_active:
                login(request, user)
                # products = Product.objects.all()
                # return render(request, 'shop/index.html' ,{'products':products})
                print("logging in user")
                return HttpResponseRedirect('/jewellery/')
            else:
                return render(request, 'shop/login.html', {'error_message':"your account disabled"})
        else:
            return render(request, 'shop/login.html')
    return render(request, 'shop/login.html')

def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {'form':form}
    # return render(request, 'shop/login.html', context)
    return HttpResponseRedirect('/jewellery')

def detailproduct(request, product_id):
    product = Product.objects.get(pk = product_id)
    ctgs = Category.objects.all()
    revpr = ReviewProduct.objects.all()[::-1]
    if product:
        context = {'product':product, 'user':request.user, 'ctgs':ctgs, 'revpr':revpr}
        return render(request, 'shop/detail.html', context)

def saveReview(request, product_id):
    form = ReviewForm(request.POST)
    productRev = Product.objects.get(pk = product_id)
    if form.is_valid():
        reviews = form.save(commit=False)
        reviews.user = request.user
        reviews.product = productRev
        reviews.review = form.cleaned_data['review']
        reviews.rating = form.cleaned_data['rating']
        reviews.save()
        return HttpResponseRedirect('/detail/' + product_id)

def removeFromCart(request, buy_id):
    print(buy_id)
    buyPr = ItemPurchase.objects.get(pk = buy_id)
    buyPr.delete()
    return HttpResponseRedirect('/cart')

def checkout(request):
    buyItems = ItemPurchase.objects.all()
    form = ShoppingDetailForm(request.POST)
    # productRev = Product.objects.get(pk = product_id)
    print("hey in custormer detail")
    if form.is_valid():
        cstDetail = form.save(commit=False)
        cstDetail.full_name = form.cleaned_data['full_name']
        cstDetail.street = form.cleaned_data['street']
        cstDetail.town = form.cleaned_data['town']
        cstDetail.district = form.cleaned_data['district']
        cstDetail.state = form.cleaned_data['state']
        cstDetail.country = form.cleaned_data['country']
        cstDetail.pin = form.cleaned_data['pin']
        cstDetail.save()
        return HttpResponseRedirect('/thank/')
    return render(request, 'shop/checkout.html', {'form':form ,'buyItems':buyItems, 'user':request.user})
    # Class based Views

def showRings(request):
    rings = Products.category.objects.filter(cname = 'rings')

def about(request):
    return render(request, 'shop/about.html')

def thankYouPage(request):
    return render(request, 'shop/thank.html')

shop/templates/shop/about.html
{% extends 'shop/base.html' %}

{% block body %}
  <div class="row">
    <div class="col-md-7 col-md-offset-4 col-sm-12 col-xs-12" style="margin-top:40px;">
      <h1 class="title" style="color:gold; text-align:left;font-family:blessed;font-size:70px;">About Us</h1>
      <h3 style="color:gold; text-align:justify;font-family:sans-serif;">Myrel Jewellery Shop is an independent family jeweller with over 40 years' experience and expertise in the beautiful world of jewellery. We are passionate about offering the highest quality of service and our wealth of knowledge guarantees you and your precious jewellery will be exceptionally cared for.
</h3>
    
     
    </div>
  </div><br><br><br><br><br><br><br><br><br>

{% endblock %}

shop/templates/shop/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Python Jewellery</title>
    {% load static %}
    <link href="{% static 'shop/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'shop/bootstrap/css/style.css' %}" rel="stylesheet">
  </head>
  <body style="background-color: green">
    <!--  navbar starts -->
    <nav class="" style="border-radius:0px !important;margin-bottom:0px; background-color: black;">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'shop:home' %}"><span id="lione" style="color: red;">Python Jewellery Shop</span></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-center">
              <li><a href="{% url 'shop:home' %}"><span id="" style="color: red">Home </span><span class="sr-only">(current)</span></a></li>
              <li><a href="{% url 'shop:home' %}"><span id="lione" style="color: red">Rings & Neklace </span></a></li>
              
              <li><a href="{% url 'shop:about' %}"><span id="lione" style="color: red">About </span></a></li>
              {% if user.username %} <li><a href="{% url 'shop:logout' %}"><span id="lione" style="color: red">Logout {{user.username}}</span></a></li>{% endif %}
              <li><a href="{% url 'shop:cart' %}"><span class="glyphicon glyphicon-shopping-cart" style="color:red;"></span></a></li>
            </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <!--  navbar ends -->
    {% block body %}{% endblock %}
    <hr class="divider">
    <center><footer style="color:white;margin-left:70px;">&copy Python Online Jewellery Shop System 2021 | All Rights Reserved</footer></center>
    <hr class="divider">

    <script src="{% static 'shop/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'shop/bootstrap/js/bootstrap.min.js' %}"></script>
  </body>
</html>
<!-- <span class="badge">{{ length }}</span> -->

shop/templates/shop/cart.html
{% extends 'shop/base.html' %}

{% block body %}

<div class="container" style="padding-top:70px;">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="panel panel-info">
        <div class="panel-heading">
          <div class="panel-title">
            <div class="row">
              <div class="col-md-6">
                <h4><span class="glyphicon glyphicon-shopping-cart"></span> Cart</h4>
              </div>
              <div class="col-md-6">
                <a href="{% url 'shop:home' %}" class="btn btn-primary pull-right">Continue Shopping</a>
              </div>
            </div>
          </div>
        </div>
        <div class="panel-body">
          {% for item in buyList %}
            {% if item.user.username == user.username %}
            <div class="row">
              <div class="col-md-2 col-sm-12">
                <img src="{{ item.product.p_photo.url }}" alt="photo" width="20%"/>
              </div>
              <div class="col-md-6 col-sm-12">
                <h3><strong>{{ item.product.p_name }}</strong></h3>
                <!-- <h4><small>{{ item.product.p_detail }}</small></h4> -->
                <h4>Price : <strong>₹{% widthratio item.quantity 1 item.product.p_cost %}</strong></h4>
                <div class="dropdown">
                  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    Quantity
                    <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                    {% for i in '12345' %}
                      <li><a href="{% url 'shop:qty' i item.id %}">{{ i }}</a></li>
                    {% endfor %}
                  </ul>
                  <a href="{% url 'shop:remove' item.id %}" class="btn btn-danger">Remove</a>
                </div>
              </div>
            </div>
          <hr>
            {% endif %}
          {% endfor %}
        </div>
        <div class="panel-footer">
          <a href="{% url 'shop:checkout' %}" class="btn btn-success pull-right">Checkout</a>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

shop/templates/shop/checkout.html
{% extends 'shop/base.html' %}

{% block body %}
	<div class="container" style="padding-top:70px;">
		<div class="row">
			<div class="col-md-8 col-sm-8 col-xs-12">
				<div class="panel panel-primary">
				  <div class="panel-heading">Shopping Address</div>
				  <div class="panel-body">
						<form action="{% url 'shop:checkout' %}" method="post" enctype="multipart/form-data">
		          {% csrf_token %}
		            {% for field in form %}
		            <div class="form-group">
		              <input type="text" class="form-control" name="{{field.html_name}}" placeholder="{{field.label}}">
		            </div>
		            {% endfor %}
		          <button type="submit" class="btn btn-success" style="width:100%;">Proceed</button>
		        </form>
				  </div>
				</div>
			</div>
			<div class="col-md-4 col-sm-4 col-xs-12">
				<div class="panel panel-success">
				  <div class="panel-heading">
						<span class="pull-right"><a href="{% url 'shop:cart' %}">Edit List</a></span>
						Review Order
					</div>
				  <div class="panel-body">
						{% for buy in buyItems %}
						{% if buy.is_purchased == True and buy.user == user %}
				    <h4>{{ buy.product.p_name }}</h4>
						<h5>₹{% widthratio buy.quantity 1 buy.product.p_cost %}</h5>
						<hr>
						{% endif %}
						{% endfor %}
				  </div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

shop/templates/shop/detail.html
{% extends 'shop/base.html' %}

{% block body %}
<div class="container" style="padding-top:70px;">
  <div class="row">
    <div class="col-md-3 col-sm-3 col-xs-12">
      <p class="lead" style="color:gold;">Category</p>
      <div class="list-group">
        {% for ctg in ctgs %}
        <a href="#" class="list-group-item
          {% if ctg.c_name == product.category.c_name %}
            active
          {% endif %}">
          {{ ctg.c_name }}
        </a>
        {% endfor %}
      </div>
    </div>
    <div class="col-md-9 col-sm-9 col-xs-12">
      <div class="thumbnail">
        <img src="{{product.p_photo.url}}" alt="img" id="myimg">
        <div class="caption">
          <h3 class="pull-right">₹{{ product.p_cost }}</h3>
          <h3>{{ product.p_name }}</h3>
          <p>{{ product.p_detail}}</p>
          <a href="{% url 'shop:addToCart' product.id %}" class="btn btn-success">Buy Now</a>
        </div>
      </div>

      <div class="well">
        <p class="text-right"><a href="#collapseExample" class="btn btn-success" data-toggle="collapse" aria-expended="false" aria-controls="collapseEx">Leave a Review</a></p>
        <div class="collapse" id="collapseExample">
          <form action="{% url 'shop:saveReview' product.id %}" method="post">
            {% csrf_token %}
            <textarea class="form-control" name = "review" rows="3"></textarea>
            <div class="form-inline" style="margin-top:15px;">
            <div class="form-group">
            <input class="form-control" type="text" name="rating" placeholder="Rating"></input>
            <button class="btn btn-success text-right">Submit</button>
          </div>
          </div>
          </form>
        </div>
        {% for rev in revpr %}
        <div class="row">
          <div class="col-md-12">
            {% if rev.product.p_name == product.p_name %}
              <h4>{{rev.user.username}}</h4>
              {% with ''|center:rev.rating as range %}
              {% for _ in range %}
               <span class="glyphicon glyphicon-star"></span>
              {% endfor %}
              {% endwith %}
              <p>{{rev.review}}</p>
              <hr>
            {% endif %}
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>


{% endblock %}

shop/templates/shop/index.html
{% extends 'shop/base.html' %}
{% block body %}

<!-- <h2>Welcome {{user.username}}</h2>

<h3>Here are some products we offer.</h3> -->

<div class="container">
<hr class="divider">

<div class="row">
  {% for product in products %}
  <div class="col-sm-6 col-md-3 col-sm-12">
    <div class="thumbnail">
      <img src="{{ product.p_photo.url }}" alt="img" width="100%" >
      <div class="caption">
        <h3>{{ product.p_name }}</h3>
        <p>₹{{ product.p_cost }}\-</p>
        <p><a href="{% url 'shop:detail' product.id %}" method="post" class="btn btn-primary" role="button" onclick="alert('This costs {{product.p_cost}}')">Details</a>
            <a href="{% url 'shop:addToCart' product.id %}" class="btn btn-success">Add to Cart</a>
        </p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
<hr class="divider">
</div>
<!-- <a href="{% url 'shop:logout' %}">Logout</a> -->

{% endblock %}

shop/templates/shop/login.html
{% extends 'shop/base.html' %}
{% block body %}
{% if error_message %}
  <p>
    <strong>{{ error_message }}</strong>
  </p>
{% endif %}

<center><div class="row" style="padding-top:40px; margin-top: 70px;">
  <div class="col-md-6 col-md-offset-3  col-xs-12">
    <h1 id="heading" style="color: white"></h1>
    <div class="panel panel-info" >
      <div class="panel-heading"style="background-color: black; color: white" >
        <center><h3>Please Login</h3></center>
      </div>
      <div class="panel-body">
        <form action="{% url 'shop:login' %}" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group">
            <!-- <label for="exampleInputEmail1">Username</label> -->
            <input type="username" class="form-control" name="username" placeholder="Username">
          </div>
          <div class="form-group">
            <!-- <label for="exampleInputPassword1">Password</label> -->
            <input type="password" class="form-control" name="password" placeholder="Password">
          </div>
          <button type="submit" class="btn btn-danger" style="width:100%;">Submit</button>
        </form>
        <h3>Not Registered? <a href="{% url 'shop:register'%}">Register Here</a></h3>
      </div>
    </div>

  </div>
  

</div>
</center>
{% endblock %}

shop/templates/shop/register.html
{% extends 'shop/base.html' %}
{% block body %}
{% if error_message %}
  <p>
    <strong>{{ error_message }}</strong>
  </p>
{% endif %}

<div class="row" style="padding-top:40px; margin-top: 70px;">
  <div class="col-md-6 col-md-offset-3 col-sm-6 col-xs-12">
   
    <div class="panel panel-info">
      <div class="panel-heading"style="background-color: black; color: white" >
       <center> <h3>Please Register</h3></center>
      </div>
      <div class="panel-body">
        <form action="{% url 'shop:register' %}" method="post" enctype="multipart/form-data">
          {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
              <input type="{{field.html_name}}" class="form-control" name="{{field.html_name}}" placeholder="{{field.label}}">
            </div>
            {% endfor %}
          <button type="submit" class="btn btn-danger" style="width:100%;">Register</button>
        </form>
      </div>
    </div>

  </div>
</div>

{% endblock %}

shop/templates/shop/thank.html
{% extends 'shop/base.html' %}

{% block body %}
	<dir class="row">
		<div class="col-md-8 col-md-offset-3 col-sm-12 col-xs-12" style="margin-top:40px;">
			<h1 class="heading" style="color:gold;">Thanks for taking interest in our company. There are more products you may like. </h1>
			<a class="btn btn-success btn-lg" href="{% url 'shop:home' %}">Continue Shopping</a>
		</div>
	</dir>
{% endblock %}